# Generated by Django 5.0.7 on 2024-07-22 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
