# Generated by Django 5.0.7 on 2024-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_resume_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='body_view',
            field=models.TextField(default='nimadir'),
            preserve_default=False,
        ),
    ]
