# Generated by Django 5.0.7 on 2024-07-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_resume_body_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='body_view',
        ),
    ]
